/* eslint-disable @next/next/no-img-element -- user-provided remote avatars are intentionally not sent through the image optimizer */
import Link from "next/link";
import {notFound} from "next/navigation";
import {ExternalLink,LogIn,Pencil,Star,Trash2} from "lucide-react";
import {db} from "@/lib/db";
import {requireUser} from "@/lib/auth";
import {deleteAccount,toggleFavorite} from "@/app/actions";
import {Header} from "@/components/header";
import {maskEmail,maskPhone,safeUrl} from "@/lib/utils";
function Row({label,value}:{label:string;value?:string|null}){return value?<div className="detail-row"><span>{label}</span><strong>{value}</strong></div>:null}
export default async function Detail({params}:{params:Promise<{id:string}>}){await requireUser();const{id}=await params;const a=await db.account.findUnique({where:{id},include:{platform:true,tags:{include:{tag:true}}}});if(!a)notFound();const profile=safeUrl(a.profileUrl),login=safeUrl(a.loginUrl??a.platform.defaultLoginUrl),manage=safeUrl(a.managementUrl??a.platform.defaultManageUrl);return <><Header/><main className="shell narrow"><Link href="/">← 所有账号</Link><section className="detail-hero" style={{"--accent":a.platform.color} as React.CSSProperties}><div className="avatar big">{a.avatarUrl?<img src={a.avatarUrl} alt=""/>:a.displayName.slice(0,1)}</div><div><p className="eyebrow">{a.platform.name}</p><h1>{a.displayName}</h1><p>{a.username?`@${a.username.replace(/^@/,"")}`:a.platformUserId||"手工账号"}</p><div className="tags">{a.tags.map(({tag})=><span key={tag.id}>{tag.name}</span>)}</div></div><form action={toggleFavorite.bind(null,id)}><button className="icon-button"><Star fill={a.favorite?"currentColor":"none"}/></button></form></section><div className="detail-actions">{profile&&<a className="button primary" href={profile} target="_blank"><ExternalLink size={16}/>打开主页</a>}{login&&<a className="button" href={login} target="_blank"><LogIn size={16}/>登录</a>}{manage&&<a className="button" href={manage} target="_blank">管理入口</a>}<Link className="button" href={`/accounts/${id}/edit`}><Pencil size={16}/>编辑</Link></div><div className="detail-grid"><section><h2>身份信息</h2><Row label="平台 UID" value={a.platformUserId}/><Row label="用户名" value={a.username}/><Row label="邮箱" value={maskEmail(a.email)}/><Row label="手机号" value={maskPhone(a.phone)}/><Row label="简介" value={a.bio}/></section><section><h2>状态</h2><Row label="维护方式" value="手工"/><Row label="账号状态" value="未验证"/><Row label="最近更新" value={a.updatedAt.toLocaleString("zh-CN")}/><Row label="Vaultwarden" value={a.vaultItemHint}/></section></div>{a.notes&&<section className="notes"><h2>备注</h2><p>{a.notes}</p></section>}<section className="danger-zone"><div><h2>删除账号</h2><p>只删除 Account Hub 中的资料，不影响真实平台账号或 Vaultwarden。</p></div><form action={deleteAccount.bind(null,id)}><button className="button danger"><Trash2 size={16}/>确认删除</button></form></section></main></>}
